// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bebbagdiyoamqztfgdys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlYmJhZ2RpeW9hbXF6dGZnZHlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MjY5MTQsImV4cCI6MjA1OTEwMjkxNH0.rLWEF4AEU9ZWrNyuybiB3-lCGpnQgG9aU-p8zZsXGQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);